#!/bin/bash
source activate python3
runipy DatGen_DistributionFreqCondNull_Omega.ipynb OUT_DatGen_DistributionFreqCondNull_Omega.ipynb
runipy DatGen_DistributionFreqCondEins_Omega.ipynb OUT_DatGen_DistributionFreqCondEins_Omega.ipynb