#!/bin/bash
source activate python3
runipy DatGen_DistributionContinuous_constMagRatio.ipynb OUT_DatGen_DistributionContinuous_constMagRatio.ipynb
runipy DatGen_DistributionContinuous_constMeanMag.ipynb OUT_DatGen_DistributionContinuous_constMeanMag.ipynb
runipy DatGen_DistributionFreqCondEins.ipynb OUT_DatGen_DistributionFreqCondEins.ipynb
runipy DatGen_DistributionFreqCondNull.ipynb OUT_DatGen_DistributionFreqCondNull.ipynb
runipy SimDecTimeErrorRate_FreqRatio_1_MagRatio_1_FreqCondNullEins.ipynb OUT_SimDecTimeErrorRate_FreqRatio_1_MagRatio_1_FreqCondNullEins.ipynb
runipy SimDecTimeErrorRate_FreqRatio_3over2_MagRatio_4over3_FreqCondEins.ipynb OUT_SimDecTimeErrorRate_FreqRatio_3over2_MagRatio_4over3_FreqCondEins.ipynb
runipy SimDecTimeErrorRate_FreqRatio_3over2_MagRatio_4over3_FreqCondNull.ipynb OUT_SimDecTimeErrorRate_FreqRatio_3over2_MagRatio_4over3_FreqCondNull.ipynb
runipy SimDecTimeErrorRate_AbsFreq10_AbsMag4_FreqCondEins.ipynb OUT_SimDecTimeErrorRate_AbsFreq10_AbsMag4_FreqCondEins.ipynb
runipy SimDecTimeErrorRate_AbsFreq10_AbsMag4_FreqCondNull.ipynb OUT_SimDecTimeErrorRate_AbsFreq10_AbsMag4_FreqCondNull.ipynb
